CREATE DATABASE IF NOT EXISTS reviews;
USE reviews;

-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

-- Database: reviews-psql

-- DROP DATABASE IF EXISTS "reviews-psql";

CREATE DATABASE "reviews-psql"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE IF NOT EXISTS public.characteristic_reviews
(
    id integer NOT NULL,
    characteristic_id integer,
    review_id integer,
    value integer,
    CONSTRAINT characteristic_reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.characteristics
(
    id integer NOT NULL,
    product_id integer,
    name text COLLATE pg_catalog."default",
    CONSTRAINT characteristics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.photos_temp
(
    id integer,
    review_id integer,
    url text COLLATE pg_catalog."default",
    photos json
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    id integer NOT NULL,
    product_id integer,
    rating integer,
    date text COLLATE pg_catalog."default",
    summary text COLLATE pg_catalog."default",
    body text COLLATE pg_catalog."default",
    recommend boolean,
    reported boolean,
    reviewer_name text COLLATE pg_catalog."default",
    reviewer_email text COLLATE pg_catalog."default",
    response text COLLATE pg_catalog."default",
    helpfulness integer,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reviews_photos
(
    id integer NOT NULL,
    review_id integer,
    url text COLLATE pg_catalog."default",
    CONSTRAINT reviews_photos_pkey PRIMARY KEY (id)
);
END;

COPY reviews
FROM '/Users/manueltiburcio/Desktop/SEI-RFP2207/SDC/datafiles/reviews.csv'
DELIMITER ','
CSV HEADER;

COPY reviews_photos
FROM '/Users/manueltiburcio/Desktop/SEI-RFP2207/SDC/datafiles/reviews_photos.csv'
DELIMITER ','
CSV HEADER;

COPY characteristics
FROM '/Users/manueltiburcio/Desktop/SEI-RFP2207/SDC/datafiles/characteristics.csv'
DELIMITER ','
CSV HEADER;

COPY characteristic_reviews
FROM '/Users/manueltiburcio/Desktop/SEI-RFP2207/SDC/datafiles/characteristic_reviews.csv'
DELIMITER ','
CSV HEADER;